/**
 *  \file probConst.h (interface file)
 *
 *  \brief Problem name: Smokers
 *
 *  Problem simulation parameters.
 *
 *  \author Nuno Lau - December 2019
 */

#ifndef PROBCONST_H_
#define PROBCONST_H_

/* Generic parameters */
 
/** \brief total number of ingredients */
#define  NUMINGREDIENTS   3
/** \brief total number of smokers */
#define  NUMSMOKERS       3

/** \brief total number of orders to be generated by agent, each order has 2 different ingredients */
#define  NUMORDERS        5

/** \brief TOBBACO ingredient id */
#define  TOBACCO          0
/** \brief MATCHES ingredient id */
#define  MATCHES          1 
/** \brief PAPER ingredient id  */
#define  PAPER            2

/** \brief id of smoker that always has TOBACCO */
#define  HAVETOBACCO      0
/** \brief id of smoker that always has MATCHES */
#define  HAVEMATCHES      1 
/** \brief id of smoker that always has PAPER */
#define  HAVEPAPER        2


/* Agent state constants */

/** \brief agent initial state, preparing pack of 2 ingredients */
#define  PREPARING        1
/** \brief agent waiting for smoker to finish rolling cigarette */
#define  WAITING_CIG      2
/** \brief agent is closing factory */
#define  CLOSING_A        3

/* Wachers state constants */

/** \brief watcher waiting for ingredient (each watcher is responsible for a different ingredient) */
#define  WAITING_ING      0
/** \brief watcher updating reservations */
#define  UPDATING         1
/** \brief watcher informing smoker that he can start rolling */
#define  INFORMING        2
/** \brief watcher is closing */
#define  CLOSING_W        3

/* Smokers state constants */

/** \brief smoker is waiting for the 2 missing ingredients  */
#define  WAITING_2ING     0
/** \brief smoker is rolling cigarette  */
#define  ROLLING          1
/** \brief smoker is smoking  */
#define  SMOKING          2
/** \brief smoker is closing  */
#define  CLOSING_S        3


#endif /* PROBCONST_H_ */
